---
- view:
    name: QA
    view-type: list
    description: |
      Test jobs
    filter-executors: true
    filter-queue: true
    job-name:
      -'ui-autotests'
      -'rest-autotests'
      -'appium-autotests'
    columns:
      - status
      - weather
      - job
      - last-success
      - last-failure
      - last-duration
      - build-button